name: Lint
on: push
jobs:
    Prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm install
            - name: Run Prettier
              run: npm run prettier
