name: Release
on:
  push:
    branches:
      - master
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:

      - name: Add plugin for eslint commits
        run: npm install --no-save conventional-changelog-eslint

      - name: Release to GitHub
        run: npx semantic-release
