name: Release on NPM & GitHub
on:
    workflow_run:
        workflows: ["Validate"]
        types: [completed]
        branches: master

permissions: write-all
jobs:
    Release:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Add plugin for eslint commits
              run: npm install --no-save conventional-changelog-eslint

            - name: Release to GitHub
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GIT_AUTHOR_NAME: deploy-bot
                  GIT_AUTHOR_EMAIL: deploy-bot@github.com
                  GIT_COMMITTER_NAME: deploy-bot
                  GIT_COMMITTER_EMAIL: deploy-bot@github.com
