name: Validate
on:
    push:
permissions: read-all
jobs:
    Prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install NPM Modules
              run: npm install

            - name: Run Prettier
              run: npm run prettier

    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install NPM Modules
              run: npm install

            - name: Run tests
              run: npm test

            - name: Code Coverage Report
              uses: romeovs/lcov-reporter-action@v0.2.11
              with:
                lcov-file: ./coverage/lcov.info
